import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Shawn Birring",
  description: "Generated by shawn",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark bg-background text-foreground">
        {children}
      </body>
    </html>
  );
}
